title : The Personal Blog of Jirka Maršík
tagline: I am not NLP
author :
  name : Jiří Maršík
  email : jiri.marsik89@gmail.com
  github : jirkamarsik
  twitter : jirkamarsik
  feedburner : jirkamarsik

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
